"""Durable run lifecycle contract foundation."""

from .canonical import canonical_json, parse_canonical_object, sha256_canonical
from .clock import Clock, ManualClock, SystemClock
from .events import build_event, calculate_event_sha256, verify_event_chain
from .exceptions import (
    EventChainError,
    IdempotencyConflictError,
    LeaseError,
    LeaseExpiredError,
    LeaseOwnershipError,
    LifecycleError,
    LifecycleValidationError,
    OptimisticConcurrencyError,
    RepositoryConflictError,
    StaleFencingTokenError,
    TransitionRejected,
)
from .idempotency import (
    compute_command_fingerprint,
    compute_semantic_idempotency_key,
    effective_idempotency_key,
    semantic_command_payload,
)
from .lease import LeaseManager
from .models import (
    SCHEMA_VERSION,
    CanonicalJsonObject,
    CommandExecutionResult,
    DecisionEvidence,
    DuplicateCommandEvidence,
    EffectResult,
    EvidenceReference,
    FindingSeverity,
    HashBinding,
    IdempotencyRecord,
    LifecycleSnapshot,
    LifecycleValidationFinding,
    LifecycleValidationReport,
    RunAggregate,
    RunCommand,
    RunCommandType,
    RunEvent,
    RunLease,
    RunPhase,
    RunStatus,
    TransitionDecision,
    TransitionRule,
)
from .replay import replay_events
from .repository import InMemoryLifecycleRepository
from .service import LifecycleService
from .transitions import (
    TRANSITION_MATRIX,
    TRANSITION_RULES,
    TransitionEngine,
    transition_matrix_as_dicts,
)
from .validation import validate_lifecycle

__all__ = [
    "SCHEMA_VERSION",
    "CanonicalJsonObject",
    "Clock",
    "CommandExecutionResult",
    "DecisionEvidence",
    "DuplicateCommandEvidence",
    "EffectResult",
    "EventChainError",
    "EvidenceReference",
    "FindingSeverity",
    "HashBinding",
    "IdempotencyConflictError",
    "IdempotencyRecord",
    "InMemoryLifecycleRepository",
    "LeaseError",
    "LeaseExpiredError",
    "LeaseManager",
    "LeaseOwnershipError",
    "LifecycleError",
    "LifecycleService",
    "LifecycleSnapshot",
    "LifecycleValidationError",
    "LifecycleValidationFinding",
    "LifecycleValidationReport",
    "ManualClock",
    "OptimisticConcurrencyError",
    "RepositoryConflictError",
    "RunAggregate",
    "RunCommand",
    "RunCommandType",
    "RunEvent",
    "RunLease",
    "RunPhase",
    "RunStatus",
    "StaleFencingTokenError",
    "SystemClock",
    "TRANSITION_MATRIX",
    "TRANSITION_RULES",
    "TransitionDecision",
    "TransitionEngine",
    "TransitionRejected",
    "TransitionRule",
    "build_event",
    "calculate_event_sha256",
    "canonical_json",
    "compute_command_fingerprint",
    "compute_semantic_idempotency_key",
    "effective_idempotency_key",
    "parse_canonical_object",
    "replay_events",
    "semantic_command_payload",
    "sha256_canonical",
    "transition_matrix_as_dicts",
    "validate_lifecycle",
    "verify_event_chain",
]
