from __future__ import annotations

from enum import StrEnum


class DataRole(StrEnum):
    RAW = "RAW"
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    HOLDOUT = "HOLDOUT"
    PROSPECTIVE_FEATURES = "PROSPECTIVE_FEATURES"
    PROSPECTIVE_PREDICTIONS = "PROSPECTIVE_PREDICTIONS"
    ACTUALS = "ACTUALS"
    METADATA = "METADATA"


class AccessOperation(StrEnum):
    READ = "READ"
    FIT_MODEL = "FIT_MODEL"
    FIT_SCALER = "FIT_SCALER"
    FIT_ENCODER = "FIT_ENCODER"
    SELECT_FEATURES = "SELECT_FEATURES"
    TUNE = "TUNE"
    TRANSFORM = "TRANSFORM"
    CALIBRATE = "CALIBRATE"
    PREDICT = "PREDICT"
    LOCK_PREDICTION = "LOCK_PREDICTION"
    READ_ACTUALS = "READ_ACTUALS"
    SCORE = "SCORE"
    REGISTER = "REGISTER"
    PROMOTE = "PROMOTE"


class Stage(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    OOF = "OOF"
    HOLDOUT = "HOLDOUT"
    PROSPECTIVE = "PROSPECTIVE"
    SCORING = "SCORING"
    REGISTRATION = "REGISTRATION"
    PROMOTION = "PROMOTION"


class AccessDecision(StrEnum):
    PASS = "PASS"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class StateKind(StrEnum):
    MODEL = "MODEL"
    SCALER = "SCALER"
    ENCODER = "ENCODER"
    FEATURE_SELECTOR = "FEATURE_SELECTOR"
    CALIBRATOR = "CALIBRATOR"
    HPO_RESULT = "HPO_RESULT"


class FoldRole(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"


class FindingSeverity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"


class FindingCode(StrEnum):
    FIT_SCOPE_VIOLATION = "FIT_SCOPE_VIOLATION"
    HOLDOUT_LEAKAGE = "HOLDOUT_LEAKAGE"
    PROSPECTIVE_ACTUAL_LEAKAGE = "PROSPECTIVE_ACTUAL_LEAKAGE"
    FUTURE_AVAILABILITY_VIOLATION = "FUTURE_AVAILABILITY_VIOLATION"
    OOF_ORDER_VIOLATION = "OOF_ORDER_VIOLATION"
    STATE_PROVENANCE_MISMATCH = "STATE_PROVENANCE_MISMATCH"
    STATE_USED_BEFORE_FIT = "STATE_USED_BEFORE_FIT"
    EVENT_ID_DUPLICATE = "EVENT_ID_DUPLICATE"
    EVENT_SEQUENCE_GAP = "EVENT_SEQUENCE_GAP"
    EVENT_PARENT_MISSING = "EVENT_PARENT_MISSING"
    EVENT_GRAPH_CYCLE = "EVENT_GRAPH_CYCLE"
    TIMESTAMP_ORDER_VIOLATION = "TIMESTAMP_ORDER_VIOLATION"
    DATASET_HASH_MISMATCH = "DATASET_HASH_MISMATCH"
    LOCK_BEFORE_PREDICT_MISSING = "LOCK_BEFORE_PREDICT_MISSING"
    ACTUAL_READ_BEFORE_LOCK = "ACTUAL_READ_BEFORE_LOCK"
    SCORE_BEFORE_ACTUAL_READ = "SCORE_BEFORE_ACTUAL_READ"
    LEDGER_HASH_MISMATCH = "LEDGER_HASH_MISMATCH"
    RUN_ID_MISMATCH = "RUN_ID_MISMATCH"
    EVENT_COUNT_MISMATCH = "EVENT_COUNT_MISMATCH"
    EVENT_TIME_BOUNDARY_MISMATCH = "EVENT_TIME_BOUNDARY_MISMATCH"
    EVENT_PARENT_NOT_PREVIOUS = "EVENT_PARENT_NOT_PREVIOUS"
    EVENT_ORDER_MISMATCH = "EVENT_ORDER_MISMATCH"
    TUNE_SCOPE_VIOLATION = "TUNE_SCOPE_VIOLATION"
    HPO_FOLD_HASH_MISSING = "HPO_FOLD_HASH_MISSING"
    OOF_SEED_MISSING = "OOF_SEED_MISSING"
    OOF_SEED_SCOPE_MISMATCH = "OOF_SEED_SCOPE_MISMATCH"
    ACTUAL_IDENTITY_MISMATCH = "ACTUAL_IDENTITY_MISMATCH"
    ACTUAL_STATE_REUSE = "ACTUAL_STATE_REUSE"
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
