"""Status and classification enums for third-party evidence contracts."""

from __future__ import annotations

from enum import StrEnum


class EvidenceStatus(StrEnum):
    NOT_PROVIDED = "NOT_PROVIDED"
    OPERATOR_ASSERTED = "OPERATOR_ASSERTED"
    LOCALLY_TIMESTAMPED = "LOCALLY_TIMESTAMPED"
    EXTERNALLY_TIMESTAMPED_UNVERIFIED = "EXTERNALLY_TIMESTAMPED_UNVERIFIED"
    EXTERNALLY_TIMESTAMPED_VERIFIED = "EXTERNALLY_TIMESTAMPED_VERIFIED"
    SIGNATURE_UNVERIFIED = "SIGNATURE_UNVERIFIED"
    SIGNATURE_VERIFIED = "SIGNATURE_VERIFIED"
    OFFICIAL_SOURCE_UNVERIFIED = "OFFICIAL_SOURCE_UNVERIFIED"
    OFFICIAL_SOURCE_VERIFIED = "OFFICIAL_SOURCE_VERIFIED"
    CORRECTED = "CORRECTED"
    REVOKED = "REVOKED"


class TimestampAuthority(StrEnum):
    NONE = "NONE"
    OPERATOR = "OPERATOR"
    LOCAL_SYSTEM = "LOCAL_SYSTEM"
    RFC3161_TSA = "RFC3161_TSA"
    TRANSPARENCY_LOG = "TRANSPARENCY_LOG"
    BLOCKCHAIN_ANCHOR = "BLOCKCHAIN_ANCHOR"
    OTHER_EXTERNAL = "OTHER_EXTERNAL"


class SignatureKind(StrEnum):
    NONE = "NONE"
    HMAC = "HMAC"
    PUBLIC_KEY = "PUBLIC_KEY"
    TRANSPARENCY_LOG = "TRANSPARENCY_LOG"
    OTHER = "OTHER"


class PublicVerifiability(StrEnum):
    NONE = "NONE"
    SHARED_SECRET_ONLY = "SHARED_SECRET_ONLY"
    PUBLIC_KEY = "PUBLIC_KEY"
    TRANSPARENCY_LOG = "TRANSPARENCY_LOG"
    UNKNOWN = "UNKNOWN"


class RevisionKind(StrEnum):
    NONE = "NONE"
    ETAG = "ETAG"
    LAST_MODIFIED = "LAST_MODIFIED"
    PUBLICATION_ID = "PUBLICATION_ID"
    CONTENT_VERSION = "CONTENT_VERSION"
    GIT_COMMIT = "GIT_COMMIT"
    OTHER = "OTHER"


class VerificationDomain(StrEnum):
    TRUSTED_TIME = "TRUSTED_TIME"
    SIGNATURE = "SIGNATURE"
    ACTUAL_SOURCE = "ACTUAL_SOURCE"


class OfflineVerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    FAILED = "FAILED"
    REVOKED = "REVOKED"
