"""Stable process-boundary contracts for isolated GluonTS providers."""

from loto.adapters.gluonts.inventory import (
    CheckState,
    FormalAvailability,
    InventoryCategory,
    RuntimeInventory,
    RuntimeInventoryEntry,
    inventory_sha256,
)
from loto.adapters.gluonts.lifecycle import (
    LifecycleInvocation,
    certify_predictor_lifecycle,
)
from loto.adapters.gluonts.p6_campaign import (
    StageInvocation as P6StageInvocation,
    invoke_p6_provider,
    run_p6_campaign,
)
from loto.adapters.gluonts.p6_contract import (
    FailureCategory as P6FailureCategory,
    ModelSpec as P6ModelSpec,
    P6CampaignResult,
    P6DatasetItem,
    P6ModelLifecycle,
    P6Operation,
    P6ProviderRequest,
    P6ProviderResponse,
    P6StageEvidence,
    P6Status,
)
from loto.adapters.gluonts.p6_registry import (
    EXPECTED_MODELS as P6_EXPECTED_MODELS,
    get_model_spec as get_p6_model_spec,
    model_specs as p6_model_specs,
    registry_sha256 as p6_registry_sha256,
)
from loto.adapters.gluonts.p7_audit import (
    EXPECTED_MODELS as P7_EXPECTED_MODELS,
    audit_lane as audit_p7_lane,
    build_target_audit,
    parse_checksum_file,
    verify_checksum_inventory,
    write_target_audit,
)
from loto.adapters.gluonts.p7_contract import (
    CertificationStatus as P7CertificationStatus,
    EvidenceState as P7EvidenceState,
    P7FailureCategory,
    P7LaneAudit,
    P7ModelClassification,
    P7TargetMachineAudit,
)
from loto.adapters.gluonts.p7b_contract import (
    P7BExecutionJournal,
    P7BExecutionManifest,
    P7BExecutionState,
    P7BSourceIdentity,
    P7BStage,
    P7BStageRecord,
    P7BStageState,
)
from loto.adapters.gluonts.p7c_analysis import (
    P7CInputError,
    build_remediation_plan as build_p7c_remediation_plan,
    verify_p7b_input as verify_p7c_input,
    write_remediation_outputs as write_p7c_remediation_outputs,
)
from loto.adapters.gluonts.p7c_contract import (
    P7CInputIdentity,
    P7CPriority,
    P7CRemediationClass,
    P7CRemediationItem,
    P7CRemediationPlan,
    P7CRerunScope,
)
from loto.adapters.gluonts.p7d_bundle import (
    P7DBundleError,
    create_evidence_bundle as create_p7d_evidence_bundle,
    verify_and_extract_bundle as verify_and_extract_p7d_bundle,
    verify_evidence_bundle as verify_p7d_evidence_bundle,
)
from loto.adapters.gluonts.p7d_contract import (
    P7DBundleEntry,
    P7DBundleManifest,
    P7DVerificationReport,
    P7DVerificationState,
)
from loto.adapters.gluonts.protocol import (
    ArgumentState,
    DatasetItem,
    DeviceRequest,
    EnvironmentLane,
    GluonTSProviderRequest,
    GluonTSProviderResponse,
    PredictionRow,
    ProviderOperation,
    ProviderStatus,
    ResourcePolicy,
    TimelineTrack,
    protocol_schema_sha256,
)
from loto.adapters.gluonts.runner import (
    ProviderInvocation,
    atomic_write_bytes,
    atomic_write_json,
    invoke_provider,
    sha256_file,
)
from loto.adapters.gluonts.serialization import (
    ArtifactFile,
    LifecycleCheckState,
    LifecycleOutcome,
    PredictorArtifactManifest,
    PredictorFitSerializeResult,
    PredictorLifecycleResult,
    PredictorReloadResult,
    artifact_tree_sha256,
    fit_result_sha256,
    lifecycle_result_sha256,
    manifest_sha256,
    prediction_sha256,
    reload_result_sha256,
    sha256_json,
)
from loto.adapters.gluonts.smoke import (
    DeepARCPUSmokeResult,
    SmokeOutcome,
    smoke_sha256,
)

__all__ = [
    "ArgumentState",
    "ArtifactFile",
    "CheckState",
    "DatasetItem",
    "DeepARCPUSmokeResult",
    "DeviceRequest",
    "EnvironmentLane",
    "FormalAvailability",
    "GluonTSProviderRequest",
    "GluonTSProviderResponse",
    "InventoryCategory",
    "LifecycleCheckState",
    "LifecycleInvocation",
    "LifecycleOutcome",
    "P6CampaignResult",
    "P6DatasetItem",
    "P6FailureCategory",
    "P6ModelLifecycle",
    "P6ModelSpec",
    "P6Operation",
    "P6ProviderRequest",
    "P6ProviderResponse",
    "P6StageEvidence",
    "P6StageInvocation",
    "P6Status",
    "P6_EXPECTED_MODELS",
    "P7BExecutionJournal",
    "P7BExecutionManifest",
    "P7BExecutionState",
    "P7BSourceIdentity",
    "P7BStage",
    "P7BStageRecord",
    "P7BStageState",
    "P7CInputError",
    "P7CInputIdentity",
    "P7CPriority",
    "P7CRemediationClass",
    "P7CRemediationItem",
    "P7CRemediationPlan",
    "P7CRerunScope",
    "P7DBundleEntry",
    "P7DBundleError",
    "P7DBundleManifest",
    "P7DVerificationReport",
    "P7DVerificationState",
    "P7CertificationStatus",
    "P7EvidenceState",
    "P7FailureCategory",
    "P7LaneAudit",
    "P7ModelClassification",
    "P7TargetMachineAudit",
    "P7_EXPECTED_MODELS",
    "PredictionRow",
    "PredictorArtifactManifest",
    "PredictorFitSerializeResult",
    "PredictorLifecycleResult",
    "PredictorReloadResult",
    "ProviderInvocation",
    "ProviderOperation",
    "ProviderStatus",
    "ResourcePolicy",
    "RuntimeInventory",
    "RuntimeInventoryEntry",
    "SmokeOutcome",
    "TimelineTrack",
    "artifact_tree_sha256",
    "atomic_write_bytes",
    "atomic_write_json",
    "audit_p7_lane",
    "build_p7c_remediation_plan",
    "build_target_audit",
    "certify_predictor_lifecycle",
    "create_p7d_evidence_bundle",
    "fit_result_sha256",
    "get_p6_model_spec",
    "inventory_sha256",
    "invoke_p6_provider",
    "invoke_provider",
    "lifecycle_result_sha256",
    "manifest_sha256",
    "p6_model_specs",
    "p6_registry_sha256",
    "parse_checksum_file",
    "prediction_sha256",
    "protocol_schema_sha256",
    "reload_result_sha256",
    "run_p6_campaign",
    "sha256_file",
    "sha256_json",
    "smoke_sha256",
    "verify_and_extract_p7d_bundle",
    "verify_checksum_inventory",
    "verify_p7c_input",
    "verify_p7d_evidence_bundle",
    "write_p7c_remediation_outputs",
    "write_target_audit",
]
