from __future__ import annotations

from enum import StrEnum


class ModelImplementationStatus(StrEnum):
    IMPLEMENTED = "IMPLEMENTED"
    UNAVAILABLE = "UNAVAILABLE"
    BLOCKED = "BLOCKED"
    DEPRECATED = "DEPRECATED"


class TrialStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    UNAVAILABLE = "UNAVAILABLE"
    BLOCKED = "BLOCKED"
    CONFIG_INVALID = "CONFIG_INVALID"
    MODEL_BUILD_FAILED = "MODEL_BUILD_FAILED"
    PRIOR_PREDICTIVE_FAILED = "PRIOR_PREDICTIVE_FAILED"
    INFERENCE_FAILED = "INFERENCE_FAILED"
    NON_CONVERGED = "NON_CONVERGED"
    POSTERIOR_INVALID = "POSTERIOR_INVALID"
    PREDICTION_COLLAPSE = "PREDICTION_COLLAPSE"
    DECODE_FAILED = "DECODE_FAILED"
    LEAKAGE_DETECTED = "LEAKAGE_DETECTED"
    SENTINEL_TRIP = "SENTINEL_TRIP"
    TIMEOUT = "TIMEOUT"
    OOM = "OOM"
    HASH_MISMATCH = "HASH_MISMATCH"


class CompatibilityReason(StrEnum):
    ALLOWED = "ALLOWED"
    BACKEND_NOT_DECLARED = "BACKEND_NOT_DECLARED"
    BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
    PROFILE_BACKEND_MISMATCH = "PROFILE_BACKEND_MISMATCH"
    CONTINUOUS_SAMPLER_WITH_DISCRETE_LATENT = "CONTINUOUS_SAMPLER_WITH_DISCRETE_LATENT"
    TARGET_MODE_UNSUPPORTED = "TARGET_MODE_UNSUPPORTED"
    EXOGENOUS_FEATURES_MISSING = "EXOGENOUS_FEATURES_MISSING"
    RESOURCE_BUDGET_EXCEEDED = "RESOURCE_BUDGET_EXCEEDED"
    EXPERIMENTAL_DISABLED = "EXPERIMENTAL_DISABLED"
    MODEL_BLOCKED = "MODEL_BLOCKED"
