"""Isolated Darts discovery, evaluation, and certification contracts."""

from .artifacts import seal_predictions, verify_prediction_seal
from .campaign import (
    CandidateAggregate,
    ChampionDecision,
    MetricVector,
    OOFConfig,
    aggregate_all,
    build_expanding_folds,
    run_oof,
    select_champion,
)
from .ensemble_conformal import (
    P10_MODEL_IDENTITIES,
    BaseModelEvidence,
    ConformalCertification,
    ConformalConfig,
    EnsembleConfig,
    EnsemblePlan,
    ForecastPoint,
    IntervalMetric,
    MatrixResult,
    P10CampaignConfig,
    StackingEvidence,
    TemporalPartition,
    build_ensemble_plan,
    certify_conformal_quantiles,
    certify_naive_average,
    certify_stacking_evidence,
    compute_interval_metrics,
    p10_identity_sha256,
    run_p10_matrix,
    validate_conformal_base,
)
from .evaluation import evaluate_predictions
from .foundation_models import (
    FOUNDATION_CAPABILITIES,
    FOUNDATION_MODEL_IDENTITIES,
    FoundationCampaignConfig,
    FoundationModelConfig,
    FoundationSourceConfig,
    capability_matrix_sha256,
    run_foundation_matrix,
)
from .historical_evaluation import (
    HistoricalContractReport,
    HistoricalForecastPolicy,
    HistoricalPoint,
    HistoricalRuntimeEvidence,
    build_contract_report,
    collect_darts_runtime_evidence,
    expected_fit_origins,
    expected_origins,
)
from .protocol import DartsRequest, DartsResponse, GameGeometry
from .provenance import RunProvenance, build_run_provenance
from .regression_models import (
    REGRESSION_MODEL_IDENTITIES,
    RegressionCampaignConfig,
    RegressionLagContract,
    RegressionModelConfig,
    build_mlforecast_parity_payload,
    run_regression_matrix,
)
from .torch_models import (
    TORCH_MODEL_IDENTITIES,
    TorchCampaignConfig,
    TorchDeviceContract,
    TorchModelConfig,
    TorchParallelPolicy,
    TorchRuntimeObservation,
    TorchTrainingContract,
    build_parallel_plan,
    certify_device_use,
    run_torch_matrix,
)

__all__ = [
    "BaseModelEvidence",
    "CandidateAggregate",
    "ChampionDecision",
    "ConformalCertification",
    "ConformalConfig",
    "DartsRequest",
    "DartsResponse",
    "EnsembleConfig",
    "EnsemblePlan",
    "FOUNDATION_CAPABILITIES",
    "FOUNDATION_MODEL_IDENTITIES",
    "ForecastPoint",
    "FoundationCampaignConfig",
    "FoundationModelConfig",
    "FoundationSourceConfig",
    "GameGeometry",
    "HistoricalContractReport",
    "HistoricalForecastPolicy",
    "HistoricalPoint",
    "HistoricalRuntimeEvidence",
    "IntervalMetric",
    "MatrixResult",
    "MetricVector",
    "OOFConfig",
    "P10CampaignConfig",
    "P10_MODEL_IDENTITIES",
    "REGRESSION_MODEL_IDENTITIES",
    "RegressionCampaignConfig",
    "RegressionLagContract",
    "RegressionModelConfig",
    "RunProvenance",
    "StackingEvidence",
    "TORCH_MODEL_IDENTITIES",
    "TemporalPartition",
    "TorchCampaignConfig",
    "TorchDeviceContract",
    "TorchModelConfig",
    "TorchParallelPolicy",
    "TorchRuntimeObservation",
    "TorchTrainingContract",
    "aggregate_all",
    "build_contract_report",
    "build_ensemble_plan",
    "build_expanding_folds",
    "build_mlforecast_parity_payload",
    "build_parallel_plan",
    "build_run_provenance",
    "capability_matrix_sha256",
    "certify_conformal_quantiles",
    "certify_device_use",
    "certify_naive_average",
    "certify_stacking_evidence",
    "collect_darts_runtime_evidence",
    "compute_interval_metrics",
    "evaluate_predictions",
    "expected_fit_origins",
    "expected_origins",
    "p10_identity_sha256",
    "run_foundation_matrix",
    "run_oof",
    "run_p10_matrix",
    "run_regression_matrix",
    "run_torch_matrix",
    "seal_predictions",
    "select_champion",
    "validate_conformal_base",
    "verify_prediction_seal",
]
